name: Check PR

on: pull_request

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Spelling
        run: |
          yarn install
          yarn spell
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Linting
        run: |
          yarn install
          yarn s lint
